
package cc.mrbird.febs.webService.Mess;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "smsServicePortType", targetNamespace = "http://service.core.weikang.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SmsServicePortType {


    /**
     * 
     * @param in5
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.core.weikang.com")
    @RequestWrapper(localName = "service", targetNamespace = "http://service.core.weikang.com", className = "cc.mrbird.febs.webService.Mess.Service")
    @ResponseWrapper(localName = "serviceResponse", targetNamespace = "http://service.core.weikang.com", className = "cc.mrbird.febs.webService.Mess.ServiceResponse")
    public String service(
        @WebParam(name = "in0", targetNamespace = "http://service.core.weikang.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.core.weikang.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.core.weikang.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://service.core.weikang.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://service.core.weikang.com")
        String in4,
        @WebParam(name = "in5", targetNamespace = "http://service.core.weikang.com")
        String in5);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.core.weikang.com")
    @RequestWrapper(localName = "callBark", targetNamespace = "http://service.core.weikang.com", className = "cc.mrbird.febs.webService.Mess.CallBark")
    @ResponseWrapper(localName = "callBarkResponse", targetNamespace = "http://service.core.weikang.com", className = "cc.mrbird.febs.webService.Mess.CallBarkResponse")
    public String callBark(
        @WebParam(name = "in0", targetNamespace = "http://service.core.weikang.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.core.weikang.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.core.weikang.com")
        String in2);

}
